# Generated by Django 3.0.12 on 2021-02-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='betterbay.Calendar'),
        ),
    ]
