# Generated by Django 3.0.12 on 2021-02-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0002_auto_20210215_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betterbay.Calendar', verbose_name='event calendar'),
        ),
    ]
