# Generated by Django 3.0.12 on 2021-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0003_auto_20210215_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
