# Generated by Django 3.0.12 on 2021-02-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0004_auto_20210215_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
