# Generated by Django 3.0.12 on 2021-02-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0005_auto_20210215_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
