# Generated by Django 3.0.12 on 2021-03-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0007_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'news'},
        ),
    ]
