# Generated by Django 3.0.12 on 2021-03-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0008_auto_20210323_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
