# Generated by Django 3.0.12 on 2021-03-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterbay', '0010_remove_news_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
